[workspace]
members = [
    "crates/data",
]

[package]
name = "toml-test"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
toml-test-data = { version = "1", path = "crates/data" }
