[package]
name = "toml-test-harness"
version = "0.4.3"
description = "Cargo test harness for verifying TOML parsers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/epage/toml-test-rs"
readme = "README.md"
categories = ["development-tools:testing", "text-processing", "encoding"]
keywords = ["development", "toml"]
edition = "2021"
rust-version = "1.60.0"  # MSRV
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE*",
  "README.md",
  "examples/**/*"
]

[dependencies]
toml-test-data = { version = "1.3", path = "../data" }
toml-test = { version = "^0.3", path = "../../" }
ignore = "0.4.18"
libtest-mimic = "0.6.0"
