[package]
name = "toml-test-harness"
version = "0.2.0"
description = "Cargo test harness for verifying TOML parsers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/epage/toml-test-rs"
readme = "README.md"
categories = ["development-tools:testing", "text-processing", "encoding"]
keywords = ["development", "toml"]
edition = "2018"

[dependencies]
toml-test-data = { version = "1.0", path = "../data" }
toml-test = { version = "^0.2", path = "../../" }
ignore = "0.4"
libtest-mimic = "0.3.0"
